String vskeleton()
{
  String html = ".container {";
  html += "    position: relative;";
  html += "    width: 100%;";
  html += "    max-width: 960px;";
  html += "    margin: 0 auto;";
  html += "    padding: 0 20px;";
  html += "    box-sizing: border-box;";
  html += "}";
  html += ".column,";
  html += ".columns {";
  html += "    width: 100%;";
  html += "    float: left;";
  html += "    box-sizing: border-box;";
  html += "}";
  html += "@media (min-width: 400px) {";
  html += "    .container {";
  html += "        width: 85%;";
  html += "        padding: 0;";
  html += "    }";
  html += "}";
  html += "@media (min-width: 550px) {";
  html += "    .container {";
  html += "        width: 80%;";
  html += "    }";
  html += "    .column,";
  html += "    .columns {";
  html += "        margin-left: 4%;";
  html += "    }";
  html += "    .column:first-child,";
  html += "    .columns:first-child {";
  html += "        margin-left: 0;";
  html += "    }";
  html += "    .one.column,";
  html += "    .one.columns {";
  html += "        width: 4.66666666667%;";
  html += "    }";
  html += "    .two.columns {";
  html += "        width: 13.3333333333%;";
  html += "    }";
  html += "    .three.columns {";
  html += "        width: 22%;";
  html += "    }";
  html += "    .four.columns {";
  html += "        width: 30.6666666667%;";
  html += "    }";
  html += "    .five.columns {";
  html += "        width: 39.3333333333%;";
  html += "    }";
  html += "    .six.columns {";
  html += "        width: 48%;";
  html += "    }";
  html += "    .seven.columns {";
  html += "        width: 56.6666666667%;";
  html += "    }";
  html += "    .eight.columns {";
  html += "        width: 65.3333333333%;";
  html += "    }";
  html += "    .nine.columns {";
  html += "        width: 74.0%;";
  html += "    }";
  html += "    .ten.columns {";
  html += "        width: 82.6666666667%;";
  html += "    }";
  html += "    .eleven.columns {";
  html += "        width: 91.3333333333%;";
  html += "    }";
  html += "    .twelve.columns {";
  html += "        width: 100%;";
  html += "        margin-left: 0;";
  html += "    }";
  html += "    .one-third.column {";
  html += "        width: 30.6666666667%;";
  html += "    }";
  html += "    .two-thirds.column {";
  html += "        width: 65.3333333333%;";
  html += "    }";
  html += "    .one-half.column {";
  html += "        width: 48%;";
  html += "    }";
  html += "    .offset-by-one.column,";
  html += "    .offset-by-one.columns {";
  html += "        margin-left: 8.66666666667%;";
  html += "    }";
  html += "    .offset-by-two.column,";
  html += "    .offset-by-two.columns {";
  html += "        margin-left: 17.3333333333%;";
  html += "    }";
  html += "    .offset-by-three.column,";
  html += "    .offset-by-three.columns {";
  html += "        margin-left: 26%;";
  html += "    }";
  html += "    .offset-by-four.column,";
  html += "    .offset-by-four.columns {";
  html += "        margin-left: 34.6666666667%;";
  html += "    }";
  html += "    .offset-by-five.column,";
  html += "    .offset-by-five.columns {";
  return html;
}

String vskeleton2()
{
  String html = "        margin-left: 43.3333333333%;";
  html += "    }";
  html += "    .offset-by-six.column,";
  html += "    .offset-by-six.columns {";
  html += "        margin-left: 52%;";
  html += "    }";
  html += "    .offset-by-seven.column,";
  html += "    .offset-by-seven.columns {";
  html += "        margin-left: 60.6666666667%;";
  html += "    }";
  html += "    .offset-by-eight.column,";
  html += "    .offset-by-eight.columns {";
  html += "        margin-left: 69.3333333333%;";
  html += "    }";
  html += "    .offset-by-nine.column,";
  html += "    .offset-by-nine.columns {";
  html += "        margin-left: 78.0%;";
  html += "    }";
  html += "    .offset-by-ten.column,";
  html += "    .offset-by-ten.columns {";
  html += "        margin-left: 86.6666666667%;";
  html += "    }";
  html += "    .offset-by-eleven.column,";
  html += "    .offset-by-eleven.columns {";
  html += "        margin-left: 95.3333333333%;";
  html += "    }";
  html += "    .offset-by-one-third.column,";
  html += "    .offset-by-one-third.columns {";
  html += "        margin-left: 34.6666666667%;";
  html += "    }";
  html += "    .offset-by-two-thirds.column,";
  html += "    .offset-by-two-thirds.columns {";
  html += "        margin-left: 69.3333333333%;";
  html += "    }";
  html += "    .offset-by-one-half.column,";
  html += "    .offset-by-one-half.columns {";
  html += "        margin-left: 52%;";
  html += "    }";
  html += "}";
  html += "html {";
  html += "    font-size: 62.5%;";
  html += "}";
  html += "body {";
  html += "    font-size: 1.5em;";
  html += "    line-height: 1.6;";
  html += "    font-weight: 400;";
  html += "    font-family: \"Raleway\", \"HelveticaNeue\", \"Helvetica Neue\", Helvetica, Arial, sans-serif;";
  html += "    color: #222;";
  html += "}";
  html += "h1,";
  html += "h2,";
  html += "h3,";
  html += "h4,";
  html += "h5,";
  html += "h6 {";
  html += "    margin-top: 0;";
  html += "    margin-bottom: 2rem;";
  html += "    font-weight: 300;";
  html += "}";
  html += "h1 {";
  html += "    font-size: 4.0rem;";
  html += "    line-height: 1.2;";
  html += "    letter-spacing: -.1rem;";
  html += "}";
  html += "h2 {";
  html += "    font-size: 3.6rem;";
  html += "    line-height: 1.25;";
  html += "    letter-spacing: -.1rem;";
  html += "}";
  html += "h3 {";
  html += "    font-size: 3.0rem;";
  html += "    line-height: 1.3;";
  html += "    letter-spacing: -.1rem;";
  html += "}";
  html += "h4 {";
  html += "    font-size: 2.4rem;";
  html += "    line-height: 1.35;";
  html += "    letter-spacing: -.08rem;";
  html += "}";
  html += "h5 {";
  html += "    font-size: 1.8rem;";
  html += "    line-height: 1.5;";
  html += "    letter-spacing: -.05rem;";
  html += "}";
  html += "h6 {";
  html += "    font-size: 1.5rem;";
  html += "    line-height: 1.6;";
  html += "    letter-spacing: 0;";
  html += "}";
  html += "@media (min-width: 550px) {";
  html += "    h1 {";
  html += "        font-size: 5.0rem;";
  html += "    }";
  html += "    h2 {";
  html += "        font-size: 4.2rem;";
  html += "    }";
  return html;
}
String vskeleton3()
{
  String html = "    h3 {";
  html += "        font-size: 3.6rem;";
  html += "    }";
  html += "    h4 {";
  html += "        font-size: 3.0rem;";
  html += "    }";
  html += "    h5 {";
  html += "        font-size: 2.4rem;";
  html += "    }";
  html += "    h6 {";
  html += "        font-size: 1.5rem;";
  html += "    }";
  html += "}";
  html += "p {";
  html += "    margin-top: 0;";
  html += "}";
  html += "a {";
  html += "    color: #1EAEDB;";
  html += "}";
  html += "a:hover {";
  html += "    color: #0FA0CE;";
  html += "}";
  html += ".button,";
  html += "button,";
  html += "input[type=\"submit\"],";
  html += "input[type=\"reset\"],";
  html += "input[type=\"button\"] {";
  html += "    display: inline-block;";
  html += "    height: 38px;";
  html += "    padding: 0 30px;";
  html += "    color: #555;";
  html += "    text-align: center;";
  html += "    font-size: 11px;";
  html += "    font-weight: 600;";
  html += "    line-height: 38px;";
  html += "    letter-spacing: .1rem;";
  html += "    text-transform: uppercase;";
  html += "    text-decoration: none;";
  html += "    white-space: nowrap;";
  html += "    background-color: transparent;";
  html += "    border-radius: 4px;";
  html += "    border: 1px solid #bbb;";
  html += "    cursor: pointer;";
  html += "    box-sizing: border-box;";
  html += "}";
  html += ".button:hover,";
  html += "button:hover,";
  html += "input[type=\"submit\"]:hover,";
  html += "input[type=\"reset\"]:hover,";
  html += "input[type=\"button\"]:hover,";
  html += ".button:focus,";
  html += "button:focus,";
  html += "input[type=\"submit\"]:focus,";
  html += "input[type=\"reset\"]:focus,";
  html += "input[type=\"button\"]:focus {";
  html += "    color: #333;";
  html += "    border-color: #888;";
  html += "    outline: 0;";
  html += "}";
  html += ".button.button-primary,";
  html += "button.button-primary,";
  html += "input[type=\"submit\"].button-primary,";
  html += "input[type=\"reset\"].button-primary,";
  html += "input[type=\"button\"].button-primary {";
  html += "    color: #FFF;";
  html += "    background-color: #33C3F0;";
  html += "    border-color: #33C3F0;";
  html += "}";
  html += ".button.button-primary:hover,";
  html += "button.button-primary:hover,";
  html += "input[type=\"submit\"].button-primary:hover,";
  html += "input[type=\"reset\"].button-primary:hover,";
  html += "input[type=\"button\"].button-primary:hover,";
  html += ".button.button-primary:focus,";
  html += "button.button-primary:focus,";
  html += "input[type=\"submit\"].button-primary:focus,";
  html += "input[type=\"reset\"].button-primary:focus,";
  html += "input[type=\"button\"].button-primary:focus {";
  html += "    color: #FFF;";
  html += "    background-color: #1EAEDB;";
  html += "    border-color: #1EAEDB;";
  html += "}";
  html += "input[type=\"email\"],";
  html += "input[type=\"number\"],";
  html += "input[type=\"search\"],";
  html += "input[type=\"text\"],";
  html += "input[type=\"tel\"],";
  html += "input[type=\"url\"],";
  html += "input[type=\"password\"],";
  html += "textarea,";
  html += "select {";
  html += "    height: 38px;";
  html += "    padding: 6px 10px;";
  html += "    background-color: #fff;";
  html += "    border: 1px solid #D1D1D1;";
  html += "    border-radius: 4px;";
  return html;
}

String vskeleton4()
{
  String html = "    box-shadow: none;";
  html += "    box-sizing: border-box;";
  html += "}";
  html += "input[type=\"email\"],";
  html += "input[type=\"number\"],";
  html += "input[type=\"search\"],";
  html += "input[type=\"text\"],";
  html += "input[type=\"tel\"],";
  html += "input[type=\"url\"],";
  html += "input[type=\"password\"],";
  html += "textarea {";
  html += "    -webkit-appearance: none;";
  html += "    -moz-appearance: none;";
  html += "    appearance: none;";
  html += "}";
  html += "textarea {";
  html += "    min-height: 65px;";
  html += "    padding-top: 6px;";
  html += "    padding-bottom: 6px;";
  html += "}";
  html += "input[type=\"email\"]:focus,";
  html += "input[type=\"number\"]:focus,";
  html += "input[type=\"search\"]:focus,";
  html += "input[type=\"text\"]:focus,";
  html += "input[type=\"tel\"]:focus,";
  html += "input[type=\"url\"]:focus,";
  html += "input[type=\"password\"]:focus,";
  html += "textarea:focus,";
  html += "select:focus {";
  html += "    border: 1px solid #33C3F0;";
  html += "    outline: 0;";
  html += "}";
  html += "label,";
  html += "legend {";
  html += "    display: block;";
  html += "    margin-bottom: .5rem;";
  html += "    font-weight: 600;";
  html += "}";
  html += "fieldset {";
  html += "    padding: 0;";
  html += "    border-width: 0;";
  html += "}";
  html += "input[type=\"checkbox\"],";
  html += "input[type=\"radio\"] {";
  html += "    display: inline;";
  html += "}";
  html += "label>.label-body {";
  html += "    display: inline-block;";
  html += "    margin-left: .5rem;";
  html += "    font-weight: normal;";
  html += "}";
  html += "ul {";
  html += "    list-style: circle inside;";
  html += "}";
  html += "ol {";
  html += "    list-style: decimal inside;";
  html += "}";
  html += "ol,";
  html += "ul {";
  html += "    padding-left: 0;";
  html += "    margin-top: 0;";
  html += "}";
  html += "ul ul,";
  html += "ul ol,";
  html += "ol ol,";
  html += "ol ul {";
  html += "    margin: 1.5rem 0 1.5rem 3rem;";
  html += "    font-size: 90%;";
  html += "}";
  html += "li {";
  html += "    margin-bottom: 1rem;";
  html += "}";
  html += "code {";
  html += "    padding: .2rem .5rem;";
  html += "    margin: 0 .2rem;";
  html += "    font-size: 90%;";
  html += "    white-space: nowrap;";
  html += "    background: #F1F1F1;";
  html += "    border: 1px solid #E1E1E1;";
  html += "    border-radius: 4px;";
  html += "}";
  html += "pre>code {";
  html += "    display: block;";
  html += "    padding: 1rem 1.5rem;";
  html += "    white-space: pre;";
  html += "}";
  html += "th,";
  html += "td {";
  html += "    padding: 12px 15px;";
  html += "    text-align: left;";
  html += "    border-bottom: 1px solid #E1E1E1;";
  html += "}";
  html += "th:first-child,";
  html += "td:first-child {";
  return html;
}

String vskeleton5()
{
  String html = "    padding-left: 0;";
  html += "}";
  html += "th:last-child,";
  html += "td:last-child {";
  html += "    padding-right: 0;";
  html += "}";
  html += "button,";
  html += ".button {";
  html += "    margin-bottom: 1rem;";
  html += "}";
  html += "input,";
  html += "textarea,";
  html += "select,";
  html += "fieldset {";
  html += "    margin-bottom: 1.5rem;";
  html += "}";
  html += "pre,";
  html += "blockquote,";
  html += "dl,";
  html += "figure,";
  html += "table,";
  html += "p,";
  html += "ul,";
  html += "ol,";
  html += "form {";
  html += "    margin-bottom: 2.5rem;";
  html += "}";
  html += ".u-full-width {";
  html += "    width: 100%;";
  html += "    box-sizing: border-box;";
  html += "}";
  html += ".u-max-full-width {";
  html += "    max-width: 100%;";
  html += "    box-sizing: border-box;";
  html += "}";
  html += ".u-pull-right {";
  html += "    float: right;";
  html += "}";
  html += ".u-pull-left {";
  html += "    float: left;";
  html += "}";
  html += "hr {";
  html += "    margin-top: 3rem;";
  html += "    margin-bottom: 3.5rem;";
  html += "    border-width: 0;";
  html += "    border-top: 1px solid #E1E1E1;";
  html += "}";
  html += ".container:after,";
  html += ".row:after,";
  html += ".u-cf {";
  html += "    content: \"\";";
  html += "    display: table;";
  html += "    clear: both;";
  html += "}";
  html += "@media (min-width: 400px) {}";
  html += "@media (min-width: 550px) {}";
  html += "@media (min-width: 750px) {}";
  html += "@media (min-width: 1000px) {}";
  html += "@media (min-width: 1200px) {}";
  html += ".btnred {";
  html += "    color: white;";
  html += "    background-color: red;";
  html += "    border-color: red;";
  html += "}";
  html += ".btnorange {";
  html += "    color: white;";
  html += "    background-color: orange;";
  html += "    border-color: orange;";
  html += "}";

  return html;
}